import {chapters,lessons,teaching} from './content.js';
import {generate,makeRound,record} from './engine.js';
import {configured,client,user,recovery,initError,initCloud,friendly,fetchProgress,pushProgress} from './cloud.js';
import {activity} from './dashboard.js';
await initCloud();
const $=s=>document.querySelector(s), key=user?'math-garden-user-'+user.id:'math-garden-v1';
let revision=0,dirty=false,syncBusy=false,conflict=false,syncTimer=null,syncMessage=user?'Đang tải tiến độ…':'Lưu trên thiết bị';
const metaKey=key+'-sync';
try{const meta=JSON.parse(localStorage.getItem(metaKey));revision=meta?.revision||0;dirty=Boolean(meta?.dirty);}catch{}

const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,grade:5,stats:{},history:[],session:null};
function valid(s){if(!s||s.version!==1||![5,6].includes(s.grade)||!s.stats||!Array.isArray(s.history))return false;if(s.history.some(h=>!h||!Number.isFinite(Date.parse(h.date))||!Array.isArray(h.results)||h.results.some(r=>!r||!Object.hasOwn(teaching,r.id)||typeof r.ok!=='boolean')))return false;for(const [id,v] of Object.entries(s.stats)){if(!v||!Object.hasOwn(teaching,id)||!Number.isInteger(v.attempts)||v.attempts<0||!Number.isInteger(v.correct)||v.correct<0||v.correct>v.attempts||!Number.isInteger(v.streak)||v.streak<0||![1,2,3].includes(v.level)||typeof v.needsReview!=='boolean')return false;}return true;}
try{const saved=JSON.parse(localStorage.getItem(key));if(valid(saved))state=saved;}catch{}
// Session is generated locally, but imported backups never include executable content.
if(state.session&&(!Array.isArray(state.session.questions)||state.session.questions.length!==5||!Array.isArray(state.session.results)||state.session.results.length>5||state.session.questions.some(q=>!teaching[q.id]||!Array.isArray(q.steps))))state.session=null;
let view=recovery?'account':'home',lessonId=null,showAnswer=false,storageWarning=false;
const ready=()=>lessons.filter(l=>l.grade===state.grade&&teaching[l.id]);
const weak=()=>ready().filter(l=>state.stats[l.id]?.needsReview);
const label=id=>lessons.find(l=>l.id===id)?.title||id;
function persist(){try{localStorage.setItem(key,JSON.stringify(state));localStorage.setItem(metaKey,JSON.stringify({revision,dirty}));}catch{storageWarning=true;}}
function save(){dirty=Boolean(user);persist();if(user){syncMessage='Đang chờ đồng bộ';clearTimeout(syncTimer);syncTimer=setTimeout(sync,800);}updateStatus();}
function updateStatus(){const el=$('#cloud-status');if(el)el.textContent=storageWarning?'Không lưu được trên máy':syncMessage;}
async function sync(){if(!user||syncBusy||conflict)return;syncBusy=true;try{
 if(dirty){const payload=JSON.parse(JSON.stringify({...state,session:null}));dirty=false;const newRevision=await pushProgress(payload,revision);revision=newRevision;persist();}
 syncMessage=dirty?'Đang chờ đồng bộ':'✓ Đã đồng bộ';
 }catch(e){dirty=true;persist();conflict=String(e.message).includes('sync_conflict');syncMessage=conflict?'Có tiến độ mới trên máy khác • mở Tài khoản':'Chưa đồng bộ • bản trên máy được giữ';}
 finally{syncBusy=false;updateStatus();if(dirty&&!conflict&&syncMessage==='Đang chờ đồng bộ')syncTimer=setTimeout(sync,800);}}
async function loadCloud(){if(!user)return;try{const remote=await fetchProgress();conflict=false;if(dirty){if((remote?.revision||0)!==revision){conflict=true;syncMessage='Có tiến độ mới • mở Tài khoản';}else await sync();}else if(remote){if(!valid(remote.payload))throw Error('Invalid progress');const activeSession=state.session;state={...remote.payload,session:activeSession};revision=remote.revision;persist();syncMessage='✓ Đã đồng bộ';}else{revision=0;syncMessage='Tài khoản sẵn sàng';}}catch{syncMessage='Chưa tải được tiến độ • thử đồng bộ lại';conflict=true;}updateStatus();}

function button(text,action,cls=''){return `<button class="${cls}" data-action="${action}">${text}</button>`;}
function go(v){view=v;showAnswer=false;render();window.scrollTo(0,0);}
function figure(f){if(!f||![f.a,f.b].every(Number.isFinite)||(f.type==='composite'&&!Number.isFinite(f.c)))return '';let shape,labels;if(f.type==='composite'){shape='<path d="M80 25H175V100H320V170H80Z"/><path d="M80 100H175" stroke-dasharray="5 5"/>';labels=`<text x="110" y="18">${f.a} cm</text><text x="175" y="198">${f.a+f.b} cm</text><text x="2" y="90">${f.b+f.c} cm</text><text x="326" y="140">${f.b} cm</text>`;}else{shape=f.type==='triangle'?'<path d="M75 170L180 35L320 170Z"/>':f.type==='parallelogram'?'<path d="M60 170L115 35H325L270 170Z"/>':'<rect x="75" y="35" width="245" height="135"/>';shape+='<path d="M180 35V170M180 155H195V170" stroke-dasharray="5 4"/>';labels=`<text x="180" y="198">${f.a} cm</text><text x="190" y="95">${f.b} cm</text>`;}return `<svg viewBox="0 0 395 215" role="img" aria-label="Hình minh họa, kích thước ghi trong đề; không theo tỉ lệ"><g fill="#e7edbd" stroke="#507c54" stroke-width="2">${shape}</g><g font-size="16" fill="#264839">${labels}</g></svg><small>Hình minh họa không theo tỉ lệ.</small>`;}
function book(){return `<div class="row spread"><div><div class="eyebrow">TỦ SÁCH CỦA CON</div><h1>Từng bài nhỏ, hiểu thật chắc.</h1></div><label>Lớp <select id="grade"><option value="5" ${state.grade===5?'selected':''}>5 · 五年生</option><option value="6" ${state.grade===6?'selected':''}>6 · 六年生</option></select></label></div><p class="muted">${ready().length} bài có thể học ngay. Các mục “Đang biên soạn” là lộ trình bổ sung. Thứ tự có thể điều chỉnh theo sách ở trường.</p>${chapters.filter(c=>c.grade===state.grade).map((c,i)=>`<details class="chapter" ${i===0?'open':''}><summary>${String(i+1).padStart(2,'0')} · ${c.title} <small>／${c.jp}</small></summary>${c.lessons.map((l,j)=>`<div class="lesson"><div><strong>${i+1}.${j+1} ${l.title}</strong><small>${l.jp}${state.stats[l.id]?` · ${state.stats[l.id].correct}/${state.stats[l.id].attempts} câu tự đánh giá đúng`:''}</small></div>${teaching[l.id]?button(state.stats[l.id]?.needsReview?'Ôn lại':'Học bài',`lesson:${l.id}`):'<span class="tag">Đang biên soạn</span>'}</div>`).join('')}</details>`).join('')}`;}
function lesson(){const l=lessons.find(l=>l.id===lessonId),t=teaching[lessonId],q=generate(lessonId,1,()=>.25);return `<article class="study">${button('← Sách bài học','book')}<p class="eyebrow">LỚP ${l.grade} · ${l.chapter}</p><h1>${l.title}</h1><p class="muted">${l.jp} · Khoảng 10–15 phút</p><section class="card"><h2>Hôm nay con sẽ học</h2><p>${t[0]}</p><div class="formula">${t[1]}</div><p>💡 ${t[2]}</p></section><section class="card" style="margin-top:18px"><h2>Cùng xem một ví dụ</h2><p>${q.prompt}</p>${figure(q.figure)}<ol>${q.steps.map(s=>`<li>${s}</li>`).join('')}</ol><strong>Đáp án: ${q.answer} ${q.unit}</strong></section><p>Con làm ra giấy, bấm xem lời giải rồi tự đánh giá. Sau 5 câu, mình cùng tổng kết.</p>${button('Con sẵn sàng • Luyện 5 câu →',`start:${lessonId}`,'primary')}</article>`;}
function practice(){const s=state.session;if(!s)return home();const i=s.results.length;if(i===5)return summary();const q=s.questions[i];return `<article class="study"><div class="row spread"><span class="eyebrow">${escape(label(q.id))}</span><span class="pill">Câu ${i+1}/5 · Mức ${q.level}</span></div><div class="dots">${s.questions.map((_,j)=>`<span class="dot ${j<i?'done':''}"></span>`).join('')}</div><section class="card"><h1 style="font-size:28px">Thử sức nào!</h1><p class="question">${escape(q.prompt)}</p>${figure(q.figure)}<label for="note">Bài làm của con <small>(không bắt buộc, không tự chấm)</small></label><textarea id="note" placeholder="Con có thể viết phép tính ở đây hoặc làm ra giấy.">${escape(s.note||'')}</textarea>${!showAnswer?`<p>${button('Làm xong • Xem lời giải','reveal','primary')}</p>`:`<div class="answer" aria-live="polite"><h3>Cùng đối chiếu</h3><ol>${q.steps.map(t=>`<li>${escape(t)}</li>`).join('')}</ol><div class="formula">${escape(q.answer)} ${escape(q.unit)}</div><p>${teaching[q.id][2]}</p></div><h3>Con đã làm thế nào?</h3><div class="row">${button('✓ Đúng và con đã hiểu','correct','primary')}${button('↻ Sai hoặc chưa hiểu','incorrect')}</div><small>Tick thật lòng nhé. Bài sai giúp mình biết cần học lại điều gì.</small>`}</section><p>${button('Tạm nghỉ • Về hôm nay','home')}</p></article>`;}
function summary(){const s=state.session;const correct=s.results.filter(r=>r.ok).length;const wrong=[...new Set(s.results.filter(r=>!r.ok).map(r=>r.id))];return `<article class="study"><section class="hero"><span class="eyebrow">HOÀN THÀNH MỘT LƯỢT</span><h1>Con đã cố gắng rồi! 🌱</h1><div class="metric">${correct} / 5 câu đúng</div><p>Theo phần tự đánh giá của con. ${correct===5?'Lượt sau có thể thử mức cao hơn.':correct>=3?'Mình sẽ luyện thêm những dạng chưa chắc.':'Mình quay lại bài mẫu và luyện chậm hơn nhé.'}</p></section><h2>Nhìn lại từng câu</h2>${s.results.map((r,i)=>`<div class="card" style="margin:10px 0"><strong class="${r.ok?'good':'bad'}">${r.ok?'✓':'↻'} Câu ${i+1} · ${escape(label(r.id))}</strong><p>${escape(s.questions[i].prompt)}</p><small>Đáp án: ${escape(s.questions[i].answer)} ${escape(s.questions[i].unit)}</small></div>`).join('')}<h2>Lượt học tiếp theo</h2><p>${wrong.length?wrong.map(label).join(' · '):'Tiếp tục củng cố và tăng nhẹ độ khó.'}</p><div class="row">${button(wrong.length?'Ôn các dạng sai • 5 câu':'Luyện thêm • 5 câu','next-round','primary')}${button('Về trang chủ','finish')}</div>${wrong.map(id=>`<p>${button(`Xem lại: ${label(id)}`,`lesson:${id}`)}</p>`).join('')}</article>`;}
function review(){return `<h1>Ôn lại để hiểu chắc hơn.</h1><p>Những dạng con tick sai sẽ ở đây. Làm đúng liên tiếp 2 câu cùng dạng để ra khỏi danh sách ôn.</p>${weak().length?`${button('Ôn các dạng sai • 5 câu','review-start','primary')}${weak().map(l=>`<div class="card" style="margin-top:16px"><h3>${l.title}</h3><p>${teaching[l.id][2]}</p>${button('Xem lại bài mẫu',`lesson:${l.id}`)}</div>`).join('')}`:'<div class="card">Chưa có dạng cần ôn ở lớp đang chọn. Con có thể mở sách để bắt đầu học.</div>'}`;}
function progress(){return report()+ `<h2>Tiến độ theo bài học</h2><p>Kết quả do bé tự đánh giá, giúp chọn bài ôn; không phải điểm kiểm tra chính thức.</p>${lessons.filter(l=>state.stats[l.id]).map(l=>{const s=state.stats[l.id];return `<div class="lesson card"><div><strong>Lớp ${l.grade} · ${l.title}</strong><small>${s.correct}/${s.attempts} câu đúng · Mức ${s.level}</small></div><span class="tag">${s.needsReview?'Cần ôn':'Đang tiến bộ'}</span></div>`}).join('')||'<div class="card">Chưa có tiến độ. Bắt đầu bài đầu tiên nhé!</div>'}<section class="card" style="margin-top:24px"><h2>Sao lưu tiến độ</h2><p>Dữ liệu lưu trên trình duyệt này. Xuất bản sao trước khi đổi thiết bị hoặc xóa dữ liệu trình duyệt.</p>${button('Tải bản sao lưu','export')}<p><label for="import">Khôi phục từ bản sao JSON</label></p><input type="file" id="import" accept="application/json,.json"><p id="import-status" role="status"></p></section>`;}
function render(){updateStatus();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#app').innerHTML=({home,book,lesson,practice,review,progress,account,profile}[view]||home)()+(storageWarning?'<p role="alert">Không lưu được tiến độ trên trình duyệt. Hãy tải bản sao trong Tiến độ trước khi đóng trang.</p>':'');}
function start(ids){if(user&&conflict){go('account');return;}if(state.session&&state.session.results.length<5&&!confirm('Bắt đầu lượt mới sẽ bỏ lượt đang làm dở. Tiếp tục?'))return;state.session={questions:makeRound(ids,state.stats),results:[],ids,note:''};save();go('practice');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){go(b.dataset.view);return;}const action=b.dataset.action;if(!action)return;const [a,id]=action.split(':');if(['home','book','review','progress','profile','account'].includes(a))return go(a);if(a==='lesson'){lessonId=id;return go('lesson');}if(a==='start')return start([id]);if(a==='resume')return go('practice');if(a==='reveal'){showAnswer=true;return render();}if(a==='review-start')return start(weak().map(l=>l.id));if(a==='correct'||a==='incorrect'){const s=state.session;if(!s||!showAnswer||s.results.length>=5)return;const q=s.questions[s.results.length],ok=a==='correct';state.stats=record(state.stats,q.id,ok,q.level);s.results.push({id:q.id,ok});s.note='';if(s.results.length===5)state.history.push({id:crypto.randomUUID(),date:new Date().toISOString(),results:s.results.map((r,i)=>({...r,prompt:s.questions[i].prompt,answer:s.questions[i].answer,unit:s.questions[i].unit}))});save();showAnswer=false;render();window.scrollTo(0,0);return;}if(a==='finish'){state.session=null;save();return go('home');}if(a==='next-round'){const s=state.session;const wrong=[...new Set(s.results.filter(r=>!r.ok).map(r=>r.id))];return start(wrong.length?wrong:s.ids);}if(a==='export'){const blob=new Blob([JSON.stringify({...state,session:null},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='vuon-toan-tien-do.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
document.addEventListener('input',e=>{if(e.target.id==='note'&&state.session){state.session.note=e.target.value;save();}});
document.addEventListener('change',async e=>{if(e.target.id==='grade'){state.grade=Number(e.target.value);save();render();}if(e.target.id==='import'){const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error();const data=JSON.parse(await file.text());if(!valid(data))throw Error();if(!confirm('Thay tiến độ hiện tại bằng bản sao này?'))return;state={version:1,grade:data.grade,stats:data.stats,history:data.history,profile:data.profile,session:null};save();render();$('#import-status').textContent='Đã khôi phục tiến độ.';}catch{$('#import-status').textContent='Bản sao không hợp lệ. Tiến độ hiện tại được giữ nguyên.';}}});
await loadCloud();
render();
function weekly(){const a=activity(state);return `<div class="week" aria-label="Số câu hoàn thành theo ngày trong 7 ngày qua">${a.recent.map(d=>`<div><strong>${d.count}</strong><div class="bar-track"><span style="height:${Math.min(100,d.count/Math.max(5,...a.recent.map(x=>x.count))*100)}%"></span></div><small>${escape(d.label)}</small></div>`).join('')}</div>`;}
function home(){const a=activity(state),w=weak(),next=w[0]||ready().find(l=>!state.stats[l.id])||ready()[0],name=escape(state.profile?.nickname||'con'),goal=Number(state.profile?.goal)||10;return `<div class="row spread page-heading"><div><span class="eyebrow">GÓC HỌC TẬP · LỚP ${state.grade}</span><h1>Hôm nay, mình tiến thêm một bước.</h1><p class="muted">Chào ${name}! Một chút tập trung, một điều mới để khám phá.</p></div><div class="avatar">${escape(state.profile?.avatar||'🌱')}</div></div><div class="dashboard-grid"><section class="hero"><span class="hero-label">LỘ TRÌNH DÀNH CHO CON</span><h2>${escape(next.title)}</h2><p>${teaching[next.id][0]}</p><div class="row"><span class="hero-chip">◷ 10–15 phút</span><span class="hero-chip">✎ 5 câu mỗi lượt</span></div><div class="row hero-actions">${state.session?button('Tiếp tục học →','resume','primary'):button('Bắt đầu bài học →',`lesson:${next.id}`,'primary')}${button('Xem lộ trình','book')}</div><div class="hero-decoration" aria-hidden="true">△<span>＋</span>◯</div></section><section class="card goal"><span class="eyebrow">MỤC TIÊU HÔM NAY</span><div class="goal-number">${a.today}<small> / ${goal} câu</small></div><progress value="${Math.min(a.today,goal)}" max="${goal}"></progress><p>${a.today>=goal?'Đã hoàn thành mục tiêu. Con làm tốt lắm!':'Mỗi lượt 5 câu, vừa sức để học đều.'}</p>${button('Điều chỉnh mục tiêu','profile')}</section></div><div class="grid stats-grid"><div class="card"><span class="stat-icon">✎</span><div class="metric">${a.attempts}</div><small>Câu đã tự đánh giá</small></div><div class="card"><span class="stat-icon">✓</span><div class="metric">${a.attempts?Math.round(a.correct/a.attempts*100):0}%</div><small>Tỉ lệ tự đánh giá đúng</small></div><div class="card"><span class="stat-icon">↻</span><div class="metric">${w.length}</div><small>Dạng cần ôn · lớp ${state.grade}</small></div></div><div class="dashboard-grid"><section class="card"><div class="row spread"><h2>Nhịp học 7 ngày</h2><span class="pill">${a.week} câu</span></div>${weekly()}<small>Tính các lượt đã hoàn thành · Giờ Nhật Bản</small></section><section class="card"><span class="eyebrow">BƯỚC NHỎ TIẾP THEO</span><h2>${w.length?'Ôn lại, hiểu sâu hơn':'Giữ nhịp mỗi ngày'}</h2><p>${w.length?escape(w.map(l=>l.title).slice(0,2).join(' · ')):'Hãy thử một lượt học. Kết quả sẽ giúp chọn bài vừa sức cho con.'}</p>${button(w.length?'Mở sổ ôn tập':'Khám phá bài học',w.length?'review':'book')}</section></div>`;}
function report(){const a=activity(state);return `<span class="eyebrow">DÀNH CHO GIA ĐÌNH</span><h1>Nhìn thấy từng bước tiến.</h1><div class="grid"><section class="card"><div class="metric">${a.rounds}</div>Lượt học hoàn thành</section><section class="card"><div class="metric">${a.week}</div>Câu trong 7 ngày</section><section class="card"><div class="metric">${Object.values(state.stats).filter(s=>!s.needsReview&&s.attempts>=5).length}</div>Bài đã luyện ít nhất 5 câu, không cần ôn</section></div><section class="card"><h2>Lịch học gần đây</h2>${weekly()}</section><h2>Nhật ký luyện tập</h2>${state.history.slice(-10).reverse().map(h=>`<details class="chapter"><summary>${escape(new Date(h.date).toLocaleString('vi-VN',{timeZone:'Asia/Tokyo'}))} · ${h.results.filter(r=>r.ok).length}/${h.results.length} đúng</summary>${h.results.map(r=>`<div class="lesson"><div><strong>${r.ok?'✓':'↻'} ${escape(label(r.id))}</strong>${r.prompt?`<p>${escape(r.prompt)}</p><small>Đáp án: ${escape(r.answer)} ${escape(r.unit||'')}</small>`:''}</div></div>`).join('')}</details>`).join('')||'<p class="muted">Sau lượt 5 câu đầu tiên, nhật ký sẽ xuất hiện ở đây.</p>'}`;}
function profile(){return `<article class="study"><span class="eyebrow">HỒ SƠ HỌC TẬP</span><h1>Một góc học mang tên con.</h1><section class="card"><form id="profile-form"><label>Biệt danh của bé<input name="nickname" maxlength="30" value="${escape(state.profile?.nickname||'')}" placeholder="Ví dụ: Mầm Nhỏ" required></label><label>Biểu tượng<select name="avatar">${['🌱','🐱','🐼','🐰','🦊','🐧'].map(a=>`<option ${state.profile?.avatar===a?'selected':''}>${a}</option>`).join('')}</select></label><label>Lớp đang học<select name="grade"><option value="5" ${state.grade===5?'selected':''}>Lớp 5 · 五年生</option><option value="6" ${state.grade===6?'selected':''}>Lớp 6 · 六年生</option></select></label><label>Mục tiêu mỗi ngày<select name="goal">${[5,10,15,20].map(n=>`<option value="${n}" ${(state.profile?.goal||10)===n?'selected':''}>${n} câu · ${n/5} lượt</option>`).join('')}</select></label><button class="primary" type="submit">Lưu hồ sơ</button><p id="profile-status" role="status"></p></form><p class="muted">Chỉ cần biệt danh. Mỗi tài khoản hiện có một hồ sơ học sinh.</p></section></article>`;}
function account(){if(user)return `<article class="study"><span class="eyebrow">TÀI KHOẢN PHỤ HUYNH</span><h1>Góc học của gia đình.</h1><section class="card"><h2>${escape(user.email||'Tài khoản đã đăng nhập')}</h2><p>${escape(syncMessage)}</p><div class="row">${button('Đồng bộ lại','cloud-sync')}${button('Đăng xuất','signout')}</div>${conflict?`<div class="answer warn"><h3>Cần kiểm tra tiến độ trước khi học tiếp</h3><p>Thiết bị khác có thể có bản mới hơn. Tải bản sao của máy này trước, rồi tải tiến độ từ tài khoản. App không tự gộp hai bản.</p>${button('Tải bản sao máy này','export')}${button('Dùng bản trên tài khoản','cloud-load')}</div>`:''}<p>${button('Mang tiến độ khách vào tài khoản','guest-import')}</p><small>Thao tác nhập sẽ yêu cầu xác nhận nếu tài khoản đã có kết quả.</small></section>${passwordForm()}<p id="auth-status" role="status"></p></article>`;return `<div class="auth-layout"><section class="auth-intro"><span class="eyebrow">VƯỜN TOÁN · GIA ĐÌNH</span><h1>Mỗi lần học,<br>một bước trưởng thành.</h1><p>Một tài khoản để lưu hồ sơ, xem lại kết quả và tiếp tục học trên thiết bị khác khi đã đồng bộ.</p><div class="auth-feature">✓ Lịch sử từng lượt luyện</div><div class="auth-feature">✓ Theo dõi dạng cần ôn</div><div class="auth-feature">✓ Mục tiêu học vừa sức</div></section><section class="card auth-card"><h2>Chào mừng gia đình!</h2><p>Dùng email của phụ huynh để tạo tài khoản.</p>${!configured?'<div class="answer warn">Tính năng tài khoản đang chờ kích hoạt. Con vẫn có thể học và lưu tiến độ trên thiết bị.</div>':initError?`<p role="alert">${escape(initError)}</p>`:''}<form id="auth-form"><label>Email phụ huynh<input type="email" name="email" autocomplete="email" required placeholder="email@example.com" ${!configured?'disabled':''}></label><label>Mật khẩu<input type="password" name="password" autocomplete="current-password" minlength="8" required placeholder="Ít nhất 8 ký tự" ${!configured?'disabled':''}></label><button name="intent" value="login" class="primary" ${!configured?'disabled':''}>Đăng nhập</button><button name="intent" value="signup" ${!configured?'disabled':''}>Tạo tài khoản</button><button name="intent" value="reset" formnovalidate ${!configured?'disabled':''}>Quên mật khẩu?</button><p id="auth-status" role="status" aria-live="polite"></p></form><p>${button('Tiếp tục học trên thiết bị →','home')}</p><small>Mật khẩu do dịch vụ đăng nhập xử lý; app không lưu mật khẩu trong tiến độ học.</small></section></div>`;}
function passwordForm(){return `<section class="card" style="margin-top:20px"><h2>${recovery?'Đặt lại mật khẩu':'Đổi mật khẩu'}</h2><form id="password-form"><label>Mật khẩu mới<input type="password" name="password" minlength="8" autocomplete="new-password" required></label><button class="primary">Lưu mật khẩu mới</button></form></section>`;}
document.addEventListener('submit',async e=>{const form=e.target;if(!['profile-form','auth-form','password-form'].includes(form.id))return;e.preventDefault();const data=new FormData(form);if(form.id==='profile-form'){state.profile={nickname:String(data.get('nickname')).trim().slice(0,30),avatar:String(data.get('avatar')),goal:Number(data.get('goal'))};state.grade=Number(data.get('grade'));save();$('#profile-status').textContent='Đã lưu hồ sơ.';return;}const status=$('#auth-status');if(!client){status.textContent='Dịch vụ tài khoản chưa sẵn sàng.';return;}const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);status.textContent='Đang xử lý…';try{let result;const intent=e.submitter?.value;const email=String(data.get('email')||'').trim(),password=String(data.get('password')||'');const redirect=location.origin+location.pathname;if(form.id==='password-form'){result=await client.auth.updateUser({password});}else if(intent==='signup'){result=await client.auth.signUp({email,password,options:{emailRedirectTo:redirect}});}else if(intent==='reset'){if(!form.elements.email.checkValidity()){form.elements.email.reportValidity();status.textContent='Nhập email hợp lệ để nhận liên kết.';return;}result=await client.auth.resetPasswordForEmail(email,{redirectTo:redirect});}else{result=await client.auth.signInWithPassword({email,password});}if(result.error)throw result.error;form.reset();if(result.data?.session){location.reload();return;}status.textContent=form.id==='password-form'?'Đã đổi mật khẩu.':intent==='signup'?'Hãy kiểm tra email để xác nhận tài khoản, sau đó đăng nhập.':'Nếu email đã được đăng ký, liên kết đặt lại mật khẩu sẽ được gửi đến hộp thư.';}catch(error){status.textContent=friendly(error);}finally{buttons.forEach(b=>b.disabled=false);}});
document.addEventListener('click',async e=>{const a=e.target.closest('button')?.dataset.action;if(!['cloud-sync','cloud-load','signout','guest-import'].includes(a))return;const status=$('#auth-status');try{if(a==='cloud-sync'){await loadCloud();if(!conflict)await sync();render();}if(a==='cloud-load'){if(!confirm('Thay bản trên máy bằng tiến độ trên tài khoản? Hãy tải bản sao nếu cần giữ cả hai.'))return;const remote=await fetchProgress();if(!remote||!valid(remote.payload))throw Error();state={...remote.payload,session:null};revision=remote.revision;dirty=false;conflict=false;persist();syncMessage='✓ Đã tải tiến độ';go('home');}if(a==='signout'){if(dirty&&!confirm('Có tiến độ chưa đồng bộ. Bản trên máy được giữ riêng theo tài khoản. Vẫn đăng xuất?'))return;const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;location.reload();}if(a==='guest-import'){if(conflict){status.textContent='Hãy xử lý khác biệt tiến độ trước khi nhập.';return;}const guest=JSON.parse(localStorage.getItem('math-garden-v1'));if(!valid(guest)){status.textContent='Không tìm thấy tiến độ khách hợp lệ trên thiết bị.';return;}if(!confirm('Sao chép tiến độ khách vào tài khoản này, thay kết quả tài khoản hiện tại? Bản khách vẫn được giữ.'))return;state={...guest,session:null};save();await sync();render();}}catch{if(status)status.textContent='Chưa thực hiện được. Dữ liệu trên máy vẫn được giữ.';}});
window.addEventListener('online',()=>{if(user&&!conflict)sync();});
window.addEventListener('password-recovery',()=>go('account'));
