import {chapters,lessons,teaching} from './content.js';
import {generate,makeRound,record} from './engine.js';
const $=s=>document.querySelector(s), key='math-garden-v1';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,grade:5,stats:{},history:[],session:null};
function valid(s){if(!s||s.version!==1||![5,6].includes(s.grade)||!s.stats||!Array.isArray(s.history))return false;for(const [id,v] of Object.entries(s.stats)){if(!teaching[id]||!Number.isInteger(v.attempts)||v.attempts<0||!Number.isInteger(v.correct)||v.correct<0||v.correct>v.attempts||!Number.isInteger(v.streak)||v.streak<0||![1,2,3].includes(v.level)||typeof v.needsReview!=='boolean')return false;}return true;}
try{const saved=JSON.parse(localStorage.getItem(key));if(valid(saved))state=saved;}catch{}
// Session is generated locally, but imported backups never include executable content.
if(state.session&&(!Array.isArray(state.session.questions)||state.session.questions.length!==5||!Array.isArray(state.session.results)||state.session.results.length>5||state.session.questions.some(q=>!teaching[q.id]||!Array.isArray(q.steps))))state.session=null;
let view='home',lessonId=null,showAnswer=false,storageWarning=false;
const ready=()=>lessons.filter(l=>l.grade===state.grade&&teaching[l.id]);
const weak=()=>ready().filter(l=>state.stats[l.id]?.needsReview);
const label=id=>lessons.find(l=>l.id===id)?.title||id;
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageWarning=true;}}
function button(text,action,cls=''){return `<button class="${cls}" data-action="${action}">${text}</button>`;}
function go(v){view=v;showAnswer=false;render();window.scrollTo(0,0);}
function figure(f){if(!f)return '';let shape,labels;if(f.type==='composite'){shape='<path d="M80 25H175V100H320V170H80Z"/><path d="M80 100H175" stroke-dasharray="5 5"/>';labels=`<text x="110" y="18">${f.a} cm</text><text x="175" y="198">${f.a+f.b} cm</text><text x="2" y="90">${f.b+f.c} cm</text><text x="326" y="140">${f.b} cm</text>`;}else{shape=f.type==='triangle'?'<path d="M75 170L180 35L320 170Z"/>':f.type==='parallelogram'?'<path d="M60 170L115 35H325L270 170Z"/>':'<rect x="75" y="35" width="245" height="135"/>';shape+='<path d="M180 35V170M180 155H195V170" stroke-dasharray="5 4"/>';labels=`<text x="180" y="198">${f.a} cm</text><text x="190" y="95">${f.b} cm</text>`;}return `<svg viewBox="0 0 395 215" role="img" aria-label="Hình minh họa, kích thước ghi trong đề; không theo tỉ lệ"><g fill="#e7edbd" stroke="#507c54" stroke-width="2">${shape}</g><g font-size="16" fill="#264839">${labels}</g></svg><small>Hình minh họa không theo tỉ lệ.</small>`;}
function book(){return `<div class="row spread"><div><div class="eyebrow">TỦ SÁCH CỦA CON</div><h1>Từng bài nhỏ, hiểu thật chắc.</h1></div><label>Lớp <select id="grade"><option value="5" ${state.grade===5?'selected':''}>5 · 五年生</option><option value="6" ${state.grade===6?'selected':''}>6 · 六年生</option></select></label></div><p class="muted">${ready().length} bài có thể học ngay. Các mục “Đang biên soạn” là lộ trình bổ sung. Thứ tự có thể điều chỉnh theo sách ở trường.</p>${chapters.filter(c=>c.grade===state.grade).map((c,i)=>`<details class="chapter" ${i===0?'open':''}><summary>${String(i+1).padStart(2,'0')} · ${c.title} <small>／${c.jp}</small></summary>${c.lessons.map((l,j)=>`<div class="lesson"><div><strong>${i+1}.${j+1} ${l.title}</strong><small>${l.jp}${state.stats[l.id]?` · ${state.stats[l.id].correct}/${state.stats[l.id].attempts} câu tự đánh giá đúng`:''}</small></div>${teaching[l.id]?button(state.stats[l.id]?.needsReview?'Ôn lại':'Học bài',`lesson:${l.id}`):'<span class="tag">Đang biên soạn</span>'}</div>`).join('')}</details>`).join('')}`;}
function home(){const r=ready(), w=weak();const next=w[0]||r.find(l=>!state.stats[l.id])||r[0];const count=Object.values(state.stats).reduce((n,s)=>n+s.attempts,0);return `<section class="hero"><div class="eyebrow">MỖI NGÀY MỘT BƯỚC NHỎ</div><h1>Chào con,<br>mình cùng khám phá toán nhé!</h1><p>Hiểu công thức, thử sức từng câu và học từ những chỗ chưa đúng. Một lượt chỉ 5 câu thôi.</p><div class="row">${state.session?button('Tiếp tục lượt đang học →','resume','primary'):button('Bắt đầu bài hôm nay →',`lesson:${next.id}`,'primary')}${button('Mở sách bài học','book')}</div></section><div class="grid"><div class="card"><div class="metric">${count}</div>Câu đã luyện</div><div class="card"><div class="metric">${w.length}</div>Dạng cần ôn ở lớp ${state.grade}</div><div class="card"><div class="metric">5 câu</div>Một lượt học vừa sức</div></div><div class="row spread"><h2>Gợi ý hôm nay</h2><span class="pill">Lớp ${state.grade}</span></div><div class="card"><span class="eyebrow">${w.length?'ÔN ĐIỀU CHƯA CHẮC':'BÀI HỌC TIẾP THEO'}</span><h2>${next.title}</h2><p>${teaching[next.id][0]}</p>${button('Xem bài học',`lesson:${next.id}`)}</div><p class="muted">Chuẩn bị giấy, bút và một góc học yên tĩnh. Con tự đối chiếu đáp án; không cần nhập bài làm lên mạng.</p>`;}
function lesson(){const l=lessons.find(l=>l.id===lessonId),t=teaching[lessonId],q=generate(lessonId,1,()=>.25);return `<article class="study">${button('← Sách bài học','book')}<p class="eyebrow">LỚP ${l.grade} · ${l.chapter}</p><h1>${l.title}</h1><p class="muted">${l.jp} · Khoảng 10–15 phút</p><section class="card"><h2>Hôm nay con sẽ học</h2><p>${t[0]}</p><div class="formula">${t[1]}</div><p>💡 ${t[2]}</p></section><section class="card" style="margin-top:18px"><h2>Cùng xem một ví dụ</h2><p>${q.prompt}</p>${figure(q.figure)}<ol>${q.steps.map(s=>`<li>${s}</li>`).join('')}</ol><strong>Đáp án: ${q.answer} ${q.unit}</strong></section><p>Con làm ra giấy, bấm xem lời giải rồi tự đánh giá. Sau 5 câu, mình cùng tổng kết.</p>${button('Con sẵn sàng • Luyện 5 câu →',`start:${lessonId}`,'primary')}</article>`;}
function practice(){const s=state.session;if(!s)return home();const i=s.results.length;if(i===5)return summary();const q=s.questions[i];return `<article class="study"><div class="row spread"><span class="eyebrow">${escape(label(q.id))}</span><span class="pill">Câu ${i+1}/5 · Mức ${q.level}</span></div><div class="dots">${s.questions.map((_,j)=>`<span class="dot ${j<i?'done':''}"></span>`).join('')}</div><section class="card"><h1 style="font-size:28px">Thử sức nào!</h1><p class="question">${escape(q.prompt)}</p>${figure(q.figure)}<label for="note">Bài làm của con <small>(không bắt buộc, không tự chấm)</small></label><textarea id="note" placeholder="Con có thể viết phép tính ở đây hoặc làm ra giấy.">${escape(s.note||'')}</textarea>${!showAnswer?`<p>${button('Làm xong • Xem lời giải','reveal','primary')}</p>`:`<div class="answer" aria-live="polite"><h3>Cùng đối chiếu</h3><ol>${q.steps.map(t=>`<li>${escape(t)}</li>`).join('')}</ol><div class="formula">${escape(q.answer)} ${escape(q.unit)}</div><p>${teaching[q.id][2]}</p></div><h3>Con đã làm thế nào?</h3><div class="row">${button('✓ Đúng và con đã hiểu','correct','primary')}${button('↻ Sai hoặc chưa hiểu','incorrect')}</div><small>Tick thật lòng nhé. Bài sai giúp mình biết cần học lại điều gì.</small>`}</section><p>${button('Tạm nghỉ • Về hôm nay','home')}</p></article>`;}
function summary(){const s=state.session;const correct=s.results.filter(r=>r.ok).length;const wrong=[...new Set(s.results.filter(r=>!r.ok).map(r=>r.id))];return `<article class="study"><section class="hero"><span class="eyebrow">HOÀN THÀNH MỘT LƯỢT</span><h1>Con đã cố gắng rồi! 🌱</h1><div class="metric">${correct} / 5 câu đúng</div><p>Theo phần tự đánh giá của con. ${correct===5?'Lượt sau có thể thử mức cao hơn.':correct>=3?'Mình sẽ luyện thêm những dạng chưa chắc.':'Mình quay lại bài mẫu và luyện chậm hơn nhé.'}</p></section><h2>Nhìn lại từng câu</h2>${s.results.map((r,i)=>`<div class="card" style="margin:10px 0"><strong class="${r.ok?'good':'bad'}">${r.ok?'✓':'↻'} Câu ${i+1} · ${escape(label(r.id))}</strong><p>${escape(s.questions[i].prompt)}</p><small>Đáp án: ${escape(s.questions[i].answer)} ${escape(s.questions[i].unit)}</small></div>`).join('')}<h2>Lượt học tiếp theo</h2><p>${wrong.length?wrong.map(label).join(' · '):'Tiếp tục củng cố và tăng nhẹ độ khó.'}</p><div class="row">${button(wrong.length?'Ôn các dạng sai • 5 câu':'Luyện thêm • 5 câu','next-round','primary')}${button('Về trang chủ','finish')}</div>${wrong.map(id=>`<p>${button(`Xem lại: ${label(id)}`,`lesson:${id}`)}</p>`).join('')}</article>`;}
function review(){return `<h1>Ôn lại để hiểu chắc hơn.</h1><p>Những dạng con tick sai sẽ ở đây. Làm đúng liên tiếp 2 câu cùng dạng để ra khỏi danh sách ôn.</p>${weak().length?`${button('Ôn các dạng sai • 5 câu','review-start','primary')}${weak().map(l=>`<div class="card" style="margin-top:16px"><h3>${l.title}</h3><p>${teaching[l.id][2]}</p>${button('Xem lại bài mẫu',`lesson:${l.id}`)}</div>`).join('')}`:'<div class="card">Chưa có dạng cần ôn ở lớp đang chọn. Con có thể mở sách để bắt đầu học.</div>'}`;}
function progress(){return `<h1>Mỗi bước nhỏ đều đáng ghi nhận.</h1><p>Kết quả do bé tự đánh giá, giúp chọn bài ôn; không phải điểm kiểm tra chính thức.</p>${lessons.filter(l=>state.stats[l.id]).map(l=>{const s=state.stats[l.id];return `<div class="lesson card"><div><strong>Lớp ${l.grade} · ${l.title}</strong><small>${s.correct}/${s.attempts} câu đúng · Mức ${s.level}</small></div><span class="tag">${s.needsReview?'Cần ôn':'Đang tiến bộ'}</span></div>`}).join('')||'<div class="card">Chưa có tiến độ. Bắt đầu bài đầu tiên nhé!</div>'}<section class="card" style="margin-top:24px"><h2>Sao lưu tiến độ</h2><p>Dữ liệu lưu trên trình duyệt này. Xuất bản sao trước khi đổi thiết bị hoặc xóa dữ liệu trình duyệt.</p>${button('Tải bản sao lưu','export')}<p><label for="import">Khôi phục từ bản sao JSON</label></p><input type="file" id="import" accept="application/json,.json"><p id="import-status" role="status"></p></section>`;}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#app').innerHTML=({home,book,lesson,practice,review,progress}[view]||home)()+(storageWarning?'<p role="alert">Không lưu được tiến độ trên trình duyệt. Hãy tải bản sao trong Tiến độ trước khi đóng trang.</p>':'');}
function start(ids){if(state.session&&state.session.results.length<5&&!confirm('Bắt đầu lượt mới sẽ bỏ lượt đang làm dở. Tiếp tục?'))return;state.session={questions:makeRound(ids,state.stats),results:[],ids,note:''};save();go('practice');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){go(b.dataset.view);return;}const action=b.dataset.action;if(!action)return;const [a,id]=action.split(':');if(['home','book','review','progress'].includes(a))return go(a);if(a==='lesson'){lessonId=id;return go('lesson');}if(a==='start')return start([id]);if(a==='resume')return go('practice');if(a==='reveal'){showAnswer=true;return render();}if(a==='review-start')return start(weak().map(l=>l.id));if(a==='correct'||a==='incorrect'){const s=state.session;if(!s||!showAnswer||s.results.length>=5)return;const q=s.questions[s.results.length],ok=a==='correct';state.stats=record(state.stats,q.id,ok,q.level);s.results.push({id:q.id,ok});s.note='';if(s.results.length===5)state.history.push({date:new Date().toISOString(),results:s.results});save();showAnswer=false;render();window.scrollTo(0,0);return;}if(a==='finish'){state.session=null;save();return go('home');}if(a==='next-round'){const s=state.session;const wrong=[...new Set(s.results.filter(r=>!r.ok).map(r=>r.id))];return start(wrong.length?wrong:s.ids);}if(a==='export'){const blob=new Blob([JSON.stringify({...state,session:null},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='vuon-toan-tien-do.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
document.addEventListener('input',e=>{if(e.target.id==='note'&&state.session){state.session.note=e.target.value;save();}});
document.addEventListener('change',async e=>{if(e.target.id==='grade'){state.grade=Number(e.target.value);save();render();}if(e.target.id==='import'){const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error();const data=JSON.parse(await file.text());if(!valid(data))throw Error();if(!confirm('Thay tiến độ hiện tại bằng bản sao này?'))return;state={version:1,grade:data.grade,stats:data.stats,history:data.history,session:null};save();render();$('#import-status').textContent='Đã khôi phục tiến độ.';}catch{$('#import-status').textContent='Bản sao không hợp lệ. Tiến độ hiện tại được giữ nguyên.';}}});
render();
