import {alignTextbook} from './textbook.js';
// Original lesson content. Sequence is adaptable to the child's textbook.
const chapter=(grade,id,title,jp,items)=>({grade,id,title,jp,lessons:items.map(([key,title,jp])=>({id:key,title,jp}))});
const draftChapters=[
chapter(5,'decimal','Số nguyên và số thập phân','整数と小数', [['place','Giá trị hàng và dịch dấu phẩy','位取り'],['decimal-mul','Nhân số thập phân','小数のかけ算'],['decimal-div','Chia số thập phân','小数のわり算']]),
chapter(5,'shape','Hình học và góc','図形と角',[['congruent','Hai hình bằng nhau','合同な図形'],['angle','Tổng các góc tam giác','三角形の角'],['polygon','Góc của tứ giác và đa giác','多角形の角']]),
chapter(5,'integer','Tính chất số nguyên','整数の性質',[['even','Số chẵn và số lẻ','偶数と奇数'],['multiple','Bội và bội chung','倍数・公倍数'],['divisor','Ước và ước chung','約数・公約数']]),
chapter(5,'fraction','Phân số từng bước','分数',[['fraction-meaning','Phân số và phép chia','分数とわり算'],['reduce','Rút gọn phân số','約分'],['common','Quy đồng mẫu số','通分'],['fraction-add','Cộng phân số khác mẫu','分数のたし算'],['fraction-sub','Trừ phân số khác mẫu','分数のひき算']]),
chapter(5,'area','Đo diện tích','面積',[['rectangle','Ôn hình vuông và chữ nhật','長方形・正方形の復習'],['parallelogram','Hình bình hành','平行四辺形'],['triangle','Tam giác và đường cao','三角形'],['trapezoid','Hình thang','台形'],['rhombus','Hình thoi','ひし形'],['composite','Hình ghép chữ L','組み合わせた図形']]),
chapter(5,'volume','Thể tích','体積',[['volume-box','Hình hộp chữ nhật','直方体'],['volume-cube','Hình lập phương','立方体'],['volume-unit','Đổi đơn vị thể tích','体積の単位']]),
chapter(5,'measure','Trung bình và lượng trên một đơn vị','平均・単位量あたり',[['average','Tìm số trung bình','平均'],['unit-rate','So sánh theo một đơn vị','単位量あたりの大きさ'],['speed','Quãng đường, thời gian, vận tốc','速さ']]),
chapter(5,'percent','Tỉ lệ và phần trăm','割合',[['percent','Tính phần trăm của một lượng','百分率'],['percent-base','Tìm lượng ban đầu','もとにする量'],['chart','Biểu đồ băng và hình quạt','帯グラフ・円グラフ']]),
chapter(5,'circle5','Đa giác đều và hình tròn','正多角形と円',[['regular','Nhận biết đa giác đều','正多角形'],['circumference','Chu vi hình tròn','円周'],['solids','Hình lăng trụ và hình trụ','角柱と円柱']]),
chapter(5,'relation5','Quan hệ giữa hai đại lượng','変わり方',[['relation','Bảng biến thiên và quan hệ tỉ lệ','比例の準備']]),
chapter(6,'symmetry','Hình đối xứng','対称な図形',[['line-symmetry','Đối xứng trục','線対称'],['point-symmetry','Đối xứng tâm','点対称']]),
chapter(6,'algebra','Biểu thức có chữ','文字と式',[['expression','Thay giá trị vào biểu thức','文字を使った式']]),
chapter(6,'fraction6','Nhân và chia phân số','分数の計算',[['fraction-mul','Nhân hai phân số','分数のかけ算'],['reciprocal','Phân số nghịch đảo','逆数'],['fraction-div','Chia hai phân số','分数のわり算'],['fraction-word','Bài toán có lời văn','分数の文章題']]),
chapter(6,'ratio','Tỉ số','比',[['ratio-simple','Rút gọn tỉ số','比の値・等しい比'],['ratio-share','Chia một lượng theo tỉ số','比の利用']]),
chapter(6,'scale','Phóng to và thu nhỏ','拡大図と縮図',[['scale','Tỉ lệ bản đồ','縮尺'],['scale-draw','Vẽ hình phóng to, thu nhỏ','拡大図・縮図の作図']]),
chapter(6,'circle6','Diện tích hình tròn','円の面積',[['circle-area','Từ bán kính đến diện tích','円の面積'],['circle-composite','Diện tích hình ghép có đường tròn','円を含む図形']]),
chapter(6,'volume6','Thể tích lăng trụ và hình trụ','角柱と円柱の体積',[['prism','Diện tích đáy × chiều cao','角柱の体積'],['cylinder','Thể tích hình trụ','円柱の体積']]),
chapter(6,'proportion','Tỉ lệ thuận và tỉ lệ nghịch','比例と反比例',[['proportion','Tỉ lệ thuận và bảng số','比例'],['proportion-graph','Đồ thị tỉ lệ thuận','比例のグラフ'],['inverse','Tỉ lệ nghịch','反比例']]),
chapter(6,'data','Dữ liệu và khả năng xảy ra','データの調べ方',[['data','Trung bình, trung vị, mốt','代表値'],['frequency','Bảng tần số và biểu đồ','度数分布'],['combinations','Liệt kê không bỏ sót','場合の数']]),
chapter(6,'finish','Hành trang lên cấp hai','算数のまとめ',[['final-number','Ôn số và phép tính','数と計算'],['final-shape','Ôn hình học và đo lường','図形と測定'],['final-word','Bài toán tổng hợp','総合問題']])];
export const chapters=alignTextbook(draftChapters);
export const lessons=chapters.flatMap(c=>c.lessons.map(l=>({...l,grade:c.grade,chapter:c.title})));
export const teaching={
'place':['Nhân với 10, 100 làm mỗi chữ số có giá trị gấp 10, 100 lần.','Số × 10; số × 100','Hãy nhìn giá trị của từng hàng, không chỉ đếm chữ số.'],
'decimal-mul':['Nhân như số nguyên rồi đặt dấu phẩy theo tổng số chữ số thập phân.','1,2 × 0,3 = 0,36','Ước lượng trước: nhân với số nhỏ hơn 1 thì kết quả nhỏ đi.'],
'decimal-div':['Nhân cả số bị chia và số chia với cùng 10 hoặc 100 để số chia thành số nguyên.','3,6 ÷ 0,4 = 36 ÷ 4 = 9','Phải dịch dấu phẩy ở cả hai số.'],
'angle':['Tổng ba góc trong mọi tam giác bằng 180°.','Góc còn lại = 180° − hai góc đã biết','Cộng hai góc trước rồi lấy 180° trừ đi.'],
'reduce':['Chia cả tử và mẫu cho cùng một ước chung để giữ nguyên giá trị phân số.','6/8 = (6 ÷ 2)/(8 ÷ 2) = 3/4','Rút gọn đến khi tử và mẫu không còn ước chung lớn hơn 1.'],
'fraction-add':['Quy đồng mẫu số, cộng các tử số và giữ nguyên mẫu. Cuối cùng rút gọn.','1/2 + 1/3 = 3/6 + 2/6 = 5/6','Không cộng hai mẫu số với nhau.'],
'fraction-sub':['Quy đồng mẫu số, trừ các tử số và giữ nguyên mẫu. Cuối cùng rút gọn.','3/4 − 1/2 = 3/4 − 2/4 = 1/4','Chỉ trừ tử sau khi đã quy đồng.'],
'rectangle':['Diện tích cho biết phần mặt phẳng hình chiếm. Đếm các ô vuông theo hàng và cột.','S = chiều dài × chiều rộng','Hai độ dài phải cùng đơn vị. Kết quả ghi cm².'],
'parallelogram':['Cắt và chuyển phần tam giác ở một bên sẽ được hình chữ nhật có cùng diện tích.','S = đáy × chiều cao','Chiều cao vuông góc với đáy, không phải cạnh nghiêng.'],
'triangle':['Hai tam giác giống nhau ghép được hình bình hành cùng đáy và chiều cao.','S = đáy × chiều cao ÷ 2','Tam giác cân hay lệch đều dùng công thức này. Chiều cao luôn vuông góc với đáy.'],
'trapezoid':['Ghép hai hình thang giống nhau thành hình bình hành có đáy bằng tổng hai đáy.','S = (đáy lớn + đáy nhỏ) × chiều cao ÷ 2','Hai đáy là hai cạnh song song. Nhớ dấu ngoặc và chia 2.'],
'rhombus':['Hai đường chéo chia hình thoi thành bốn tam giác vuông.','S = đường chéo 1 × đường chéo 2 ÷ 2','Dùng độ dài toàn bộ hai đường chéo.'],
'composite':['Chia hình chữ L bằng một đường ngang thành hai hình chữ nhật không chồng nhau.','S = phần dưới + phần nhô lên','Chiều cao phần nhô lên = chiều cao toàn hình − chiều cao phần dưới.'],
'volume-box':['Một lớp có dài × rộng khối lập phương đơn vị. Nhân thêm chiều cao để đếm mọi lớp.','V = dài × rộng × cao','Đơn vị thể tích là cm³, khác với diện tích cm².'],
'volume-cube':['Hình lập phương có ba kích thước bằng nhau.','V = cạnh × cạnh × cạnh','Nhân ba lần, không phải cạnh × 3.'],
'average':['Chia đều tổng các giá trị cho số lượng giá trị.','Trung bình = tổng ÷ số lượng','Đếm đủ số giá trị, kể cả giá trị bằng 0.'],
'percent':['Phần trăm là tỉ lệ tính trên 100.','Lượng cần tìm = lượng ban đầu × phần trăm ÷ 100','20% có nghĩa là 20/100 = 0,2.'],
'circumference':['Chu vi là độ dài đường bao quanh hình tròn. Bán kính bằng một nửa đường kính.','C = đường kính × 3,14','Chu vi ghi cm, không ghi cm².'],
'expression':['Thay chữ bằng giá trị đã cho rồi thực hiện phép tính theo đúng thứ tự.','Nếu x = 4 thì 3 × x + 2 = 14','Làm nhân chia trước, cộng trừ sau.'],
'fraction-mul':['Nhân tử với tử, mẫu với mẫu rồi rút gọn.','a/b × c/d = (a × c)/(b × d)','Có thể rút gọn chéo trước khi nhân.'],
'fraction-div':['Đổi phép chia thành phép nhân với phân số nghịch đảo của số chia.','a/b ÷ c/d = a/b × d/c','Chỉ đảo phân số thứ hai. Số chia phải khác 0.'],
'circle-area':['Diện tích hình tròn phụ thuộc vào bình phương bán kính.','S = bán kính × bán kính × 3,14','Đề cho đường kính thì chia 2 để tìm bán kính trước.'],
'ratio-share':['Cộng số phần của tỉ số, tìm giá trị một phần rồi nhân với số phần cần tìm.','Chia 20 theo 2 : 3 → 1 phần = 20 ÷ 5','Hai phần cộng lại phải bằng lượng ban đầu.'],
'prism':['Các lớp song song với đáy có cùng diện tích.','V = diện tích đáy × chiều cao','Diện tích đáy ghi cm²; thể tích ghi cm³.'],
'cylinder':['Hình trụ có đáy là hình tròn. Tính diện tích đáy rồi nhân chiều cao.','V = r × r × 3,14 × h','Chiều cao là khoảng cách vuông góc giữa hai đáy.']};
