// Original exercises aligned to textbook skills, not copied worksheets.
const n=x=>String(Math.round(x*10000)/10000);
const vi=x=>n(x).replace('.',',');
const gcd=(a,b)=>b?gcd(b,a%b):a;
const frac=(a,b)=>{const d=gcd(a,b);return b/d===1?String(a/d):`${a/d}/${b/d}`;};
export const extraTeaching={};
export const extraTeachingJa={};
const generators={};
function lesson(id,v,j,formula,tipV,tipJ,fn){extraTeaching[id]=[v,formula,tipV];extraTeachingJa[id]=[j,formula,tipJ];generators[id]=fn;}
const pack=(v,j,answer,vstep,jstep,unit='')=>({prompt:v,answer:typeof answer==='number'?vi(answer):answer,steps:vstep,unit,ja:{prompt:j,answer:typeof answer==='number'?n(answer):answer,steps:jstep,unit}});
lesson('decimal-units','Đếm xem số gồm bao nhiêu phần 0,001.','0.001が何個分あるかを考えます。','0.125 = 0.001 × 125','Đừng bỏ qua chữ số 0 ở giữa.','途中の0にも気をつけましょう。',({a,b,level})=>{const k=a*10+b+(level>1?100:0);return pack(`${vi(k/1000)} gồm bao nhiêu phần 0,001?`,`${n(k/1000)}は0.001の何個分ですか。`,k,['Chia số đã cho cho 0,001.',`${vi(k/1000)} × 1000 = ${k}`],['0.001を1つ分として数えます。',`${n(k/1000)} × 1000 = ${k}`]);});
lesson('decimal-smaller','Chia cho 10 hoặc 100 làm giá trị mỗi chữ số nhỏ đi tương ứng.','10や100でわると、数字の位が下がります。','2.4 ÷ 10 = 0.24','Giữ đúng các hàng sau dấu phẩy.','小数点の位置を確かめましょう。',({a,b,level})=>{const d=level===1?10:100,x=a+b/10;return pack(`${vi(x)} ÷ ${d} = ?`,`${n(x)} ÷ ${d} を計算しましょう。`,x/d,[`Chia cho ${d}.`,`${vi(x)} ÷ ${d} = ${vi(x/d)}`],[`${d}でわると、位が${d===10?1:2}けた下がります。`,`${n(x)} ÷ ${d} = ${n(x/d)}`]);});
lesson('volume-unit','Đổi đơn vị thể tích dựa vào khối lập phương đơn vị.','体積の単位の関係を使います。','1 L = 1000 cm³; 1 m³ = 1000000 cm³','Đổi thể tích khác đổi độ dài.','長さの単位の換算と区別しましょう。',({a,level})=>{const big=level===3,d=big?1000000:1000,u=big?'m³':'L';return pack(`Đổi ${a} ${u} sang cm³.`,`${a} ${u}は何cm³ですか。`,a*d,[`1 ${u} = ${d} cm³`,`${a} × ${d} = ${a*d}`],[`1 ${u} = ${d} cm³`,`${a} × ${d} = ${a*d}`],'cm³');});
lesson('relation','Tìm giá trị của một đơn vị rồi nhân số đơn vị.','1つ分の量を求めてから、個数をかけます。','y = 4 × x','Kiểm tra hai đại lượng tăng cùng số lần.','一方が2倍なら、もう一方も2倍か調べます。',({a,b})=>pack(`Mỗi vở giá ${a*10} yên. ${b} vở giá bao nhiêu?`,`ノート1冊は${a*10}円です。${b}冊では何円ですか。`,a*b*10,[`Giá 1 vở: ${a*10} yên.`,`${a*10} × ${b} = ${a*b*10}`],[`1冊分は${a*10}円です。`,`${a*10} × ${b} = ${a*b*10}`],'円'));
lesson('proportion5-table','Điền bảng bằng một lượng không đổi trên mỗi đơn vị.','1つ分の量が一定の表を完成させます。','1 → 3; 2 → 6; 4 → 12','Không cộng một số cố định vào mọi ô.','個数に1つ分の量をかけます。',({a,b})=>pack(`Bảng số hộp → số bút: 1 → ${a}; 2 → ${2*a}; ${b+2} → ?`,`箱の数→鉛筆の本数：1→${a}、2→${2*a}、${b+2}→□。□はいくつですか。`,a*(b+2),[`Một hộp có ${a} bút.`,`${a} × ${b+2} = ${a*(b+2)}`],[`1箱には${a}本入っています。`,`${a} × ${b+2} = ${a*(b+2)}`]));
lesson('decimal-product-size','Nhân số dương với số nhỏ hơn 1 làm tích nhỏ đi; lớn hơn 1 làm tích lớn lên.','正の数に1より小さい数をかけると積は小さく、1より大きい数なら大きくなります。','8 × 0.5 < 8; 8 × 1.5 > 8','So sánh thừa số với 1 trước khi tính.','かける数を1と比べましょう。',({a,b,level})=>{const x=b/10+(level>1?1:0),sign=x<1?'<':'>';return pack(`Điền < hoặc >: ${a} × ${vi(x)} □ ${a}.`,`${a} × ${n(x)} □ ${a}。□に<か>を入れましょう。`,sign,[`${vi(x)} ${sign} 1`,`${a} × ${vi(x)} = ${vi(a*x)} ${sign} ${a}`],[`${n(x)} ${sign} 1`,`${a} × ${n(x)} = ${n(a*x)} ${sign} ${a}`]);});
lesson('decimal-laws','Dùng tính chất phân phối để tính thuận tiện.','分配法則で計算を工夫します。','0.4 × 7 + 0.4 × 3 = 0.4 × 10','Chỉ đặt chung thừa số xuất hiện ở cả hai tích.','共通の数を見つけましょう。',({a,b})=>pack(`Tính thuận tiện: ${vi(a/10)} × ${b} + ${vi(a/10)} × ${10-b}.`,`工夫して計算しましょう：${n(a/10)} × ${b} + ${n(a/10)} × ${10-b}。`,a,[`${vi(a/10)} × (${b} + ${10-b})`,`${vi(a/10)} × 10 = ${a}`],[`${n(a/10)} × (${b} + ${10-b})`,`${n(a/10)} × 10 = ${a}`]));
lesson('decimal-times','Một lượng gấp một số lần thập phân cũng được tìm bằng phép nhân.','小数倍の量も、もとの量に倍をかけて求めます。','6 × 1.5 = 9','Xác định lượng ban đầu trước.','もとにする量を確かめましょう。',({a,b})=>pack(`Dây xanh dài ${a} m. Dây đỏ dài gấp ${vi(1+b/10)} lần. Dây đỏ dài bao nhiêu?`,`青いテープは${a} mです。赤いテープはその${n(1+b/10)}倍です。赤は何mですか。`,a*(1+b/10),['Lấy độ dài ban đầu nhân số lần.',`${a} × ${vi(1+b/10)} = ${vi(a*(1+b/10))}`],['もとの長さに倍をかけます。',`${a} × ${n(1+b/10)} = ${n(a*(1+b/10))}`],'m'));
lesson('even','Số chẵn chia hết cho 2; số lẻ chia 2 dư 1.','偶数は2でわり切れ、奇数は1余ります。','18 ÷ 2 = 9; 19 ÷ 2 = 9 … 1','Nhìn chữ số hàng đơn vị.','一の位に注目しましょう。',({a,b})=>{const x=a*10+b;return pack(`${x} chia 2 dư bao nhiêu? Từ đó nhận biết chẵn hay lẻ.`,`${x}を2でわると余りはいくつですか。偶数か奇数かも考えましょう。`,x%2,[`${x} = 2 × ${Math.floor(x/2)} + ${x%2}`,x%2?'Dư 1 nên là số lẻ.':'Dư 0 nên là số chẵn。'],[`${x} = 2 × ${Math.floor(x/2)} + ${x%2}`,x%2?'余り1なので奇数です。':'余り0なので偶数です。']);});
lesson('multiple','Bội chung nhỏ nhất là bội dương nhỏ nhất chung cho hai số.','最小公倍数は、共通する正の倍数のうち最も小さい数です。','4: 4,8,12; 6: 6,12 → 12','Không nhầm bội với ước.','倍数と約数を区別しましょう。',({a,b})=>{const x=a*b/gcd(a,b);return pack(`Tìm bội chung nhỏ nhất của ${a} và ${b}.`,`${a}と${b}の最小公倍数を求めましょう。`,x,[`Các bội của ${a}: ${Array.from({length:x/a},(_,i)=>a*(i+1)).join(', ')}`,`${x} cũng chia hết cho ${b}; đó là bội chung dương đầu tiên.`],[`${a}の倍数：${Array.from({length:x/a},(_,i)=>a*(i+1)).join('、')}`,`${b}でもわり切れる最初の正の倍数は${x}です。`]);});
lesson('divisor','Ước chung lớn nhất là số lớn nhất mà cả hai số đều chia hết cho nó.','最大公約数は、両方をわり切る最も大きい数です。','12: 1,2,3,4,6,12; 8: 1,2,4,8 → 4','Liệt kê ước theo cặp.','約数を対にして探しましょう。',({a,b,c})=>{const x=a*c,y=b*c,ds=Array.from({length:Math.min(x,y)},(_,i)=>i+1).filter(d=>x%d===0&&y%d===0);return pack(`Tìm ước chung lớn nhất của ${x} và ${y}.`,`${x}と${y}の最大公約数を求めましょう。`,gcd(x,y),[`Các ước chung: ${ds.join(', ')}`,`Lớn nhất là ${gcd(x,y)}.`],[`公約数：${ds.join('、')}`,`最も大きい数は${gcd(x,y)}です。`]);});
lesson('fraction-meaning','Phép chia có thể viết thành phân số.','わり算の商は分数で表せます。','3 ÷ 4 = 3/4','Số chia là mẫu số.','わる数が分母になります。',({a,b})=>pack(`Chia đều ${a} m dây cho ${b} bạn. Mỗi bạn được bao nhiêu m? Viết phân số tối giản.`,`${a} mのテープを${b}人で等分します。1人分は何mですか。約分した分数か整数で答えましょう。`,frac(a,b),[`${a} ÷ ${b} = ${a}/${b}`,`Rút gọn: ${frac(a,b)}`],[`${a} ÷ ${b} = ${a}/${b}`,`約分すると${frac(a,b)}です。`],'m'));
lesson('fraction-decimal','Đổi phân số thành số thập phân bằng cách chia tử cho mẫu.','分子を分母でわると小数になります。','3/4 = 3 ÷ 4 = 0.75','Mẫu 2, 4, 5, 10 cho số thập phân hữu hạn.','分子をわられる数にします。',({a,b})=>{const d=[2,4,5,10][b%4];return pack(`Đổi ${a}/${d} thành số thập phân.`,`${a}/${d}を小数で表しましょう。`,a/d,[`Lấy tử ${a} chia mẫu ${d}.`,`${a} ÷ ${d} = ${vi(a/d)}`],[`分子${a}を分母${d}でわります。`,`${a} ÷ ${d} = ${n(a/d)}`]);});
lesson('common','Quy đồng bằng một mẫu số chung.','共通の分母を使って通分します。','1/2 = 3/6; 1/3 = 2/6','Nhân tử và mẫu cùng một số.','分子と分母に同じ数をかけます。',({a,b,c})=>pack(`Điền tử số: ${a}/${b} = ?/${b*c}.`,`分子を求めましょう：${a}/${b} = □/${b*c}。`,a*c,[`Mẫu nhân ${c}.`,`Tử cũng nhân ${c}: ${a} × ${c} = ${a*c}`],[`分母は${c}倍です。`,`分子も${c}倍：${a} × ${c} = ${a*c}`]));
lesson('average-total','Tổng bằng trung bình nhân số phần.','合計は平均に個数をかけて求めます。','12 × 4 = 48','Đếm cả những ngày có giá trị 0.','0の日も日数に入れます。',({a,b})=>pack(`Trong ${b} ngày, trung bình bé đọc ${a} trang/ngày. Tổng cộng bao nhiêu trang?`,`${b}日間で、1日平均${a}ページ読みました。全部で何ページですか。`,a*b,['Tổng = trung bình × số ngày.',`${a} × ${b} = ${a*b}`],['合計 = 平均 × 日数',`${a} × ${b} = ${a*b}`]));
lesson('unit-rate','So sánh giá bằng cách tính giá của một món.','1個あたりの値段で比べます。','120 ÷ 3 = 40','Chia tổng giá cho số món.','代金を個数でわります。',({a,b})=>pack(`${b} quyển vở giá ${a*b*10} yên. Một quyển giá bao nhiêu?`,`${b}冊のノートが${a*b*10}円です。1冊あたり何円ですか。`,a*10,['Giá một quyển = tổng giá ÷ số quyển.',`${a*b*10} ÷ ${b} = ${a*10}`],['1冊あたり = 代金 ÷ 冊数',`${a*b*10} ÷ ${b} = ${a*10}`],'円'));
lesson('speed','Vận tốc bằng quãng đường chia thời gian.','速さは道のりを時間でわって求めます。','120 km ÷ 2 h = 60 km/h','Thống nhất đơn vị thời gian.','時間の単位をそろえましょう。',({a,b})=>pack(`Xe đi ${a*b*10} km trong ${b} giờ. Vận tốc trung bình là bao nhiêu km/h?`,`${b}時間で${a*b*10} km進みました。平均の時速は何kmですか。`,a*10,['Vận tốc = quãng đường ÷ thời gian.',`${a*b*10} ÷ ${b} = ${a*10}`],['速さ = 道のり ÷ 時間',`${a*b*10} ÷ ${b} = ${a*10}`],'km/h'));
lesson('percentage-rate','Tỉ lệ phần trăm bằng phần được xét chia tổng rồi nhân 100.','割合を求めてから100倍して百分率で表します。','15 ÷ 20 × 100 = 75%','Xác định tổng làm mốc 100%.','もとにする量が100%です。',({a,b})=>pack(`Có ${a*b} viên bi đỏ trong tổng ${a*10} viên. Bi đỏ chiếm bao nhiêu phần trăm?`,`全部で${a*10}個の玉があり、赤は${a*b}個です。赤は全体の何%ですか。`,b*10,[`${a*b} ÷ ${a*10} = ${vi(b/10)}`,`${vi(b/10)} × 100 = ${b*10}%`],[`${a*b} ÷ ${a*10} = ${n(b/10)}`,`${n(b/10)} × 100 = ${b*10}%`],'%'));
lesson('percent-base','Tìm lượng ban đầu bằng lượng so sánh chia tỉ lệ.','もとにする量は、比べられる量を割合でわります。','24 ÷ 0.6 = 40','Đổi phần trăm sang số thập phân trước.','百分率を小数に直しましょう。',({a,b})=>pack(`${b*10}% số trang sách là ${a*b} trang. Sách có tổng bao nhiêu trang?`,`本の${b*10}%が${a*b}ページです。この本は全部で何ページですか。`,a*10,[`${b*10}% = ${vi(b/10)}`,`${a*b} ÷ ${vi(b/10)} = ${a*10}`],[`${b*10}% = ${n(b/10)}`,`${a*b} ÷ ${n(b/10)} = ${a*10}`]));
lesson('fraction-times-integer','Nhân tử với số nguyên, giữ mẫu rồi rút gọn.','分子に整数をかけ、分母はそのままにして約分します。','2/3 × 4 = 8/3','Có thể rút gọn trước khi nhân.','先に約分すると計算が楽になります。',({a,b,c})=>pack(`${a}/${b} × ${c} = ?`,`${a}/${b} × ${c} を計算しましょう。`,frac(a*c,b),[`Tử: ${a} × ${c} = ${a*c}`,`Giữ mẫu ${b}, rút gọn: ${frac(a*c,b)}`],[`分子：${a} × ${c} = ${a*c}`,`分母は${b}のまま、約分して${frac(a*c,b)}`]));
lesson('fraction-div-integer','Chia phân số cho số nguyên bằng cách nhân mẫu với số đó.','分数を整数でわるには、分母にその整数をかけます。','2/3 ÷ 4 = 2/12 = 1/6','Rút gọn kết quả.','最後に約分しましょう。',({a,b,c})=>pack(`${a}/${b} ÷ ${c} = ?`,`${a}/${b} ÷ ${c} を計算しましょう。`,frac(a,b*c),[`Mẫu: ${b} × ${c} = ${b*c}`,`${a}/${b*c} = ${frac(a,b*c)}`],[`分母：${b} × ${c} = ${b*c}`,`${a}/${b*c} = ${frac(a,b*c)}`]));
lesson('reciprocal','Hai số nghịch đảo có tích bằng 1.','積が1になる2つの数を、互いに逆数といいます。','2/3 × 3/2 = 1','Số 0 không có nghịch đảo.','0には逆数がありません。',({a,b})=>pack(`Tìm nghịch đảo của ${a}/${b}.`,`${a}/${b}の逆数を求めましょう。`,frac(b,a),[`Đổi chỗ tử và mẫu: ${b}/${a}`,`${a}/${b} × ${b}/${a} = 1; rút gọn: ${frac(b,a)}`],[`分子と分母を入れかえて${b}/${a}`,`${a}/${b} × ${b}/${a} = 1。約分すると${frac(b,a)}`]));
lesson('ratio-simple','Chia hai số trong tỉ số cho cùng ước chung lớn nhất.','比の両方の数を最大公約数でわります。','6 : 9 = 2 : 3','Giữ nguyên thứ tự hai lượng.','比の順序を変えないようにしましょう。',({a,b,c})=>{const d=gcd(a,b);return pack(`Rút gọn tỉ số ${a*c} : ${b*c}.`,`${a*c} : ${b*c}を簡単な比にしましょう。`,`${a/d} : ${b/d}`,[`Chia cả hai số cho ${d*c}.`,`${a*c} ÷ ${d*c} : ${b*c} ÷ ${d*c} = ${a/d} : ${b/d}`],[`両方を${d*c}でわります。`,`${a*c} ÷ ${d*c} : ${b*c} ÷ ${d*c} = ${a/d} : ${b/d}`]);});
export function generateSupplement(id,level,rng){if(!generators[id])return null;const ri=(lo,hi)=>lo+Math.floor(rng()*(hi-lo+1));const q=generators[id]({a:ri(2,level===1?7:level===2?12:20),b:ri(2,9),c:ri(2,6),level});return {id,level,figure:null,...q};}
lesson('volume-composite','Tách khối ghép thành hai hình hộp không chồng lên nhau, rồi cộng thể tích.','重ならない2つの直方体に分け、体積をたします。','V = V₁ + V₂','Chiều sâu của cả hai phần bằng nhau. Không tính phần chung hai lần.','2つの部分の奥行きは同じです。重ねて数えないようにしましょう。',({a,b,c,level})=>{const width=a+b,depth=c,lower=b,upper=a,rise=c,total=lower+rise,v1=width*depth*lower,v2=upper*depth*rise;
 const q=pack(`Khối bậc thang có chiều ngang toàn bộ ${width} cm, chiều sâu ${depth} cm, cao toàn bộ ${total} cm. Phần dưới cao ${lower} cm; phần trên rộng ${upper} cm và có cùng chiều sâu. Tính thể tích.`,`階段形の立体です。全体の横は${width} cm、奥行きは${depth} cm、全体の高さは${total} cmです。下の部分の高さは${lower} cm、上の部分の横は${upper} cmで、奥行きは同じです。体積を求めましょう。`,v1+v2,[`Phần dưới: ${width} × ${depth} × ${lower} = ${v1} cm³`,`Phần trên cao: ${total} − ${lower} = ${rise} cm`,`Phần trên: ${upper} × ${depth} × ${rise} = ${v2} cm³`,`Cộng: ${v1} + ${v2} = ${v1+v2} cm³`],[`下の部分：${width} × ${depth} × ${lower} = ${v1} cm³`,`上の部分の高さ：${total} − ${lower} = ${rise} cm`,`上の部分：${upper} × ${depth} × ${rise} = ${v2} cm³`,`合計：${v1} + ${v2} = ${v1+v2} cm³`],'cm³');
 if(level===3){q.steps.push(`Cách khác: ${width} × ${depth} × ${total} − ${b} × ${depth} × ${rise} = ${v1+v2} cm³`);q.ja.steps.push(`別の方法：${width} × ${depth} × ${total} − ${b} × ${depth} × ${rise} = ${v1+v2} cm³`);}
 q.figure={type:'volume-composite',width,depth,lower,upper,total};return q;});
